name: for prod

on:
  push:
    branches:
      - "prod"

  workflow_dispatch:

jobs:
  display_secrets:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: echo secrets
        run: echo ${{ secrets.USER_NAME }} 
     
