name: sample

on: 
  workflow_dispatch:
    
jobs:
  build_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: echo secrets
        run: echo ${{ secrets.USER_NAME }}   
